### ISSUE TITLE
Can't update cover image

### ISSUE THREAD

**Issue by nathangallardo** [leafo/itch.io#102]
Hi!

I uploaded a new cover image for my game, and although it shows the correct, new one on the edit page, the store page shows the old one. I've tried deleting the old one, deleting all pictures, uploading new ones etc. but it just won't change the cover image that displays on the store page.

My page is http://houseofwire.itch.io/prowl

The cover image should be a black/white/grey image with PROWL written on it, but it won't change from the screenshot of the game that originally had set as the cover image

**Comment by leafo** [comment]
Should be fixed now. Thanks
