### ISSUE TITLE
Allow filtering of adult content

### ISSUE THREAD

**Issue by qirien** [leafo/itch.io#109]
Some users may not want to see games with adult content (especially when the graphic for the game that shows up in search results is suggestive).  Also, allowing games to be marked as such would help gamers make an informed decision about what games they do/don't want to play.

**Comment by Deozaan** [comment]
Is there a way to vote on these things? :+1:

**Comment by Smurf999** [comment]
Especially those really gay Robert Yang games, I don't want to see that while browsing for actual games.

**Comment by Guard13007** [comment]
Yes please! Normally I don't mind, but I don't go to Itch for those kind of games, and there's enough of them that I want to be able to filter them out.

@Deozaan The way to "vote" is pretty much what you've done. xD Comment showing your support / ideas.

**Comment by Deozaan** [comment]
I suspect that the erotic content should probably not be visible by default (unless you want to start age-screening visitors to the site). It may even be that itch.io is violating some laws against providing/showing erotic content to minors.

I'd like to make it clear that while I personally am not interested in seeing the erotic games, I have no problem with them being available to others who are interested in it. I'd just like an option to not have to see them. And I'd like that option to be the default so that I can recommend to family and friends of any age that they check out itch.io for some great games without having to worry about exposing them to erotic content.

**Comment by bdjnk** [comment]
Mr. Yang's phallic obsession aside, this is important functionality for any site with user generated content. The potential trouble is in man hours for curating content, but this can seemingly be avoided relying on user flagging and automation.

**Comment by qirien** [comment]
I think most creators would also be happy to self-rate their own material, clicking a "Mature Content" or similar box when posting their game if necessary.  Search results could exclude such material unless the user specifically requests it.

Since itch.io is registered in the U.S., I believe it is illegal to distribute this material to minors:
"It is illegal for an individual to knowingly use interactive computer services to display obscenity in a manner that makes it available to a minor less than 18 years of age (See 47 U.S.C. § 223(d) –Communications Decency Act of 1996, as amended by the PROTECT Act of 2003)" 
( http://www.justice.gov/criminal-ceos/citizens-guide-us-federal-law-obscenity )

**Comment by lugalias** [comment]
Please allow this! Especially for when I'm browsing in public, like a college classroom or café. I don't want someone glancing over and seeing me browsing men sucking popsicles or furry porn, when I'm just trying to find unique indie games.

**Comment by fasterthanlime** [comment]
So, we've deployed metadata2 ([announcement](http://blog.itch.io/post/123832634614/better-game-classification)), which allows devs and admins to mark games as nsfw, the games marked are excluded from search, browse, collections, unless the person browsing is signed in and has opted into viewing NSFW content in their user settings.

Keep in mind, no content filtering/rating system is perfect, so if something slips through, there's a "Report" link on the bottom of pages, just for that.
