### ISSUE TITLE
Make game URLs case insensitive

### ISSUE THREAD

**Issue by slowriot** [leafo/itch.io#114]
All game URLs are lowercase, but going to their differently cased counterparts returns a 404.

Example: http://voxelstorm.itch.io/advertcity works, http://voxelstorm.itch.io/AdvertCity returns 404

Since URLs are sometimes typed from memory, occasionally the upper-cased version ends up being sent in emails or pasted elsewhere, and end up not working.  The preferred behaviour would be for the incorrectly cased URLs to either redirect to their lowercase counterparts, or simply display the content regardless of case.

**Comment by josefnpat** [comment]
:+1:

**Comment by leafo** [comment]
They are now case insensitive.
