### ISSUE TITLE
Feature Request: Comments/Feedback

### ISSUE THREAD

**Issue by JetLennit** [leafo/itch.io#115]
When posting my game, I noticed that there is no area for feedback/comments on the game. Is there any reason this isn't already in? Do I have to use an external source for bug tracking? This is my first (and probably my only) feature request so I'm not sure how to write it, thus why this is probably written wrong. 

-Jet

**Comment by leafo** [comment]
This is the right place to write this. This feature is in development. Thanks for the feedback.
