### ISSUE TITLE
Game doesn't load fully

### ISSUE THREAD

**Issue by IkarusRises** [leafo/itch.io#117]
I've downloaded the game (Royals), and unzipped the file. However, when I attempt to open it all I get is a white screen like this. 

![image](https://cloud.githubusercontent.com/assets/12193481/7425474/e856fc04-ef76-11e4-8a84-6825476f160e.png)

The game won't load beyond this point. Please help, thank you.

**Comment by fasterthanlime** [comment]
This isn't the right place to report game-specific issues, please contact the game's developer instead.
