### ISSUE TITLE
Twitter card does not reflect tiered bundle price

### ISSUE THREAD

**Issue by elisee** [leafo/itch.io#120]
Hey itchies :)

This is a bit late for our bundle but I thought it's worth fixing for future bundles. The GameDev Starter Pack page correctly reflects that the bundle is tiered by stating "Buy up to 4 items starting at $20.00":

![image](https://cloud.githubusercontent.com/assets/446986/7534919/d0f4ceba-f57f-11e4-8af3-78d856666cd9.png)

But the Twitter card still says "$20.00 for 4 games":

![image](https://cloud.githubusercontent.com/assets/446986/7534917/c634dc22-f57f-11e4-8fce-ffdc2b42ccff.png)

Here are the meta tags returned:

    <meta name="twitter:description" content="GameDev Starter Pack, $20.00 for 4 games">
    ...
    <meta property="og:description" content="GameDev Starter Pack, $20.00 for 4 games">
    <meta name="description" content="GameDev Starter Pack, $20.00 for 4 games">

**Comment by fasterthanlime** [comment]
Good catch!

**Comment by elisee** [comment]
In the same vein, https://itch.io/bundles says "4 items for $20.00"

![image](https://cloud.githubusercontent.com/assets/446986/7540848/06d1d2b8-f5b1-11e4-80b0-ba8cd96e8b8b.png)

**Comment by leafo** [comment]
Thanks for the reports. Sorry about the trouble. There were a few people who purchased the wrong tier who want to upgrading and we're going to have something out soon to help them out. Are you okay if these upgraded purchases happen after the bundle is over?

**Comment by leafo** [comment]
Should be fixed everywhere now. Thanks

**Comment by elisee** [comment]
@leafo yes, no problem if it happens afterwards. It's great if you can offer them to upgrade :)
