### ISSUE TITLE
'Support this Game' modal no longer pops up on web games

### ISSUE THREAD

**Issue by LindseyB** [leafo/itch.io#124]
For example when you click "Support This Game" the overlay for the modal appears, but the modal it's isn't present. This appears to happen on all of the pages I have checked in Chrome and Safari on OS X (eg: http://berzee.itch.io/the-secret-of-gargoyle-manor).

Screenshot of what I have been seeing: 
![screen shot 2015-05-11 at 11 35 04 am](https://cloud.githubusercontent.com/assets/33750/7568637/d21fd56a-f7d1-11e4-900e-bc0ac32898dc.png)

**Comment by fasterthanlime** [comment]
Confirmed, fix incoming

**Comment by fasterthanlime** [comment]
Fix deployed, thanks for reporting!
