### ISSUE TITLE
iframes in user pages not rendered correctly

### ISSUE THREAD

**Issue by slowriot** [leafo/itch.io#126]
This is a similar issue to https://github.com/leafo/itch.io/issues/86 but affecting user profile pages instead of game pages.

The wysiwyg editor on http://itch.io/user/settings#tab=profile allows you to insert iframes and previews them correctly:
![](http://i.imgur.com/XxFYEY8.png)

However, the page itself just renders plain text:
![](http://i.imgur.com/a4MbMlN.png)

It would be very useful to be able to include iframes on user pages, as this could then serve as a main landing page for a brand - I am currently considering redirecting our .com landing page straight to our itch.io page, but that's only viable if we can include the various social media widgets we currently use, as well as any other widgets we might add in future.

**Comment by slowriot** [comment]
Would just like to bump this as I'm sure it would be a quick fix, and it's the only thing keeping me from redirecting my primary .com to itch.io...

**Comment by leafo** [comment]
Does this still not work for you?

This is what's whitelisted for the iframe tag:

```moonscript
whitelist.tags.iframe = {
  width: true
  height: true
  frameborder: true
  allowfullscreen: true
  scrolling: true
  src: true
  style: (text) ->
    sanitize_style text
}
```

**Comment by slowriot** [comment]
Nope, I've added the code now so you can see for yourself: http://voxelstorm.itch.io/
![](http://i.imgur.com/8W1zPNi.png)

Unless I'm doing something wrong with the iframe here?

**Comment by slowriot** [comment]
This appears to be fixed now, thank you!

**Comment by leafo** [comment]
I didn't touch anything :) maybe you just had to re-apply the HTML from the markup mode?

**Comment by slowriot** [comment]
I'd done that a few times; it only seemed to start working when I added a second iframe.  Will let you know if I'm able to reproduce the problem again, but let's assume it's fixed for now :)

**Comment by slowriot** [comment]
I'd done that a few times; it only seemed to start working when I added a second iframe.  Will let you know if I'm able to reproduce the problem again, but let's assume it's fixed for now :)
