### ISSUE TITLE
Displayed on wrong monitor on Ubuntu 2 monitor system

### ISSUE THREAD

**Issue by ungerik** [leafo/itch.io#128]
Starts with the higher resolution of screen 0 but is displayed on the lower resolution screen 1. Can't access the menu on the right, because it's off screen.

displaymanager : xrandr version warning. 1.4
client has 4 screens
displaymanager screen (0)(DVI-I-1): 2560 x 1440
displaymanager screen (1)(DVI-D-0): 1920 x 1080

**Comment by ungerik** [comment]
OK, managed to start it with the right resolution for screen 1:
./FPVFreerider.x86_64 -screen-fullscreen 1 -screen-width 1920 -screen-height 1080

But how do I get it on the main screen 0?

**Comment by leafo** [comment]
Hey,

This is the issues tracker for the website http://itch.io. I suggest getting in touch with the developer if you have any issues with their game. Tell me if you have trouble contacting them.

Thanks
