### ISSUE TITLE
Gift game copies don't get a key?

### ISSUE THREAD

**Issue by Enemby** [leafo/itch.io#129]
I ran into this issue recently, regarding redeeming a key for another distributor from the purchase page.
What I noticed is that claimed game copies don't get a redeemable key, since they don't show up on the purchase page, but instead on their own page, "Claimed keys".

Relevant info:
http://itchio.tumblr.com/post/74627109892/give-steam-keys-with-your-purchases
http://i.gyazo.com/530ad36212c450d5e7d3e775b2183c0b.png (Ride the Bullet has a steam redeemable key, but since my copy is claimed, I can't see it.)

**Comment by fasterthanlime** [comment]
That's correct. Claimed keys don't unlock external keys, as you could then enter a cycle of infinite-redeem between two (or more) stores. That's actually a feature!

**Comment by Enemby** [comment]
Oh! Makes sense put that way.
