### ISSUE TITLE
Screenshots panel goes under main content panel on chrome / mac os

### ISSUE THREAD

**Issue by Tavrox** [leafo/itch.io#131]
On my page with custom CSS which worked fine earlier, screenshots content is below main content.
ref : http://4edges.itch.io/lavapools & chrome & mac osX
![2015-05-26_1345](https://cloud.githubusercontent.com/assets/3044035/7811983/a2e6b122-03ae-11e5-8eb4-29293ede1422.png)

**Comment by fasterthanlime** [comment]
That's because of the responsive update, fixed the CSS on your page to accomodate it :)
