### ISSUE TITLE
Would be nice to have 404's redirect back to the profile page

### ISSUE THREAD

**Issue by slowriot** [leafo/itch.io#133]
Currently broken links like http://voxelstorm.itch.io/test bring up a 404 with a "go home" message that just leads to http://itch.io.  It would be nice if this was a link leading to the profile the 404 fell under instead, i.e. http://voxelstorm.itch.io in this case.

**Comment by Deozaan** [comment]
Good idea! I like this.

**Comment by Guard13007** [comment]
I agree, this would be nice, especially if I typo linking to one of my games, at least they might get to my profile. xD
