### ISSUE TITLE
"Checkout with" user interface uses confusing colors

### ISSUE THREAD

**Issue by Tectorum** [leafo/itch.io#143]
The "checkout with" user interface is a bit confusing for some users. The initial "Buy Now" button uses red, as shown here:
![screen shot 2015-06-07 at 12 26 57](https://cloud.githubusercontent.com/assets/5571683/8025141/961061da-0d10-11e5-8a9d-5ff62700c21b.png)

But when it comes to checking out, the options are blue, gray, and white, as shown below. I don't see a clear reason for this, and I've already had a user ask why purchasing with a credit card was disabled (since it's gray).
![screen shot 2015-06-07 at 12 25 42](https://cloud.githubusercontent.com/assets/5571683/8025131/5e990b80-0d10-11e5-9959-cdd9fe9f4d53.png)

The "How buying works" documentation shows the red=clickable & active scheme being used for checkout:
![](http://itch.io/static/images/developers/buying/thumbs/dialog.png)

Ideally, I'd like to use one color to indicate "You can click this" across the itch.io widget (i.e., for "Buy Now", "Support the Developer", and for "Checkout with"). Alternatively, I'd like to return to use one color scheme for all the payment methods so users don't have to guess why they're colored differently. Are either of these options supported by the widget currently?

**Comment by fasterthanlime** [comment]
Hey there,

I'm responsible for the color changes in the buy form :)

The rationale was:

  * Use brand colors where possible
  * Have bitcoin button be discreet (as they remain relatively niche)

On a white background, it works, imho:

![screen shot 2015-06-12 at 16 40 07](https://cloud.githubusercontent.com/assets/7998310/8132396/cdf24112-1121-11e5-9015-ae5339167634.png)

Back then, I didn't realize how it would look on dark-background widgets, so you definitely have a point.

I'm still attached to brand colors, I think they improved the looks & readability of the regular, white-bg checkout form. For dark-background widgets, we could revert to an all-red color scheme, I suppose that would be an acceptable fix for everyone? /cc @leafo

**Comment by leafo** [comment]
The different colors seems arbitrary, the only color that is actually a brand color is PayPal's. I have no issue with keeping them all red. For keeping the bitcoin button secondary I would probably just show the icon and reveal the text on hover.

I think using consistent button styles is a safe default choice unless we plan to try to track and optimize conversion rate based on these changes.

**Comment by Tectorum** [comment]
That sounds like a good overall approach. Thanks!

**Comment by fasterthanlime** [comment]
All buttons are now red.
