### ISSUE TITLE
Macos OS version of Freerider: only 8mbs of the game are downloaded and thus the game is not opening

### ISSUE THREAD

**Issue by prouso01** [leafo/itch.io#149]
Hi,
THere is an issue with me downloading the Macos version of Freerider game. I purchased the full game but I cannot download the Macos version as the download stops at 8mbs. After trying to unzip, I get a warning saying Unable to expand etc...

As I already purchased this to work on my Mac, I need to have the macos version

**Comment by leafo** [comment]
Got your support ticket.
