### ISSUE TITLE
Cannot claim game because of broken HTTP/HTTPS interaction

### ISSUE THREAD

**Issue by ssokolow** [leafo/itch.io#150]
I can't "Log in to link" because:

1. Every attempt to log in forces me to HTTPS.
2. HTTP URLs don't see my login cookies after logging in via HTTPS.
3. The game page URLs 404 if I access them over HTTPS rather than HTTP.
4. Clicking "Log in to link" after having logged in via HTTPS redirects me to the Itch.io front page without linking the game.

**Comment by leafo** [comment]
The HTTPS cookie should be available to both HTTP and HTTPS connections. (Since we don't have wildcard cert on on game pages yet). You should be able to interact with non https pages even after singing in from http. Are you using some browser extension that's changing how this works (like https everywhere maybe?)

**Comment by ssokolow** [comment]
I am running HTTPS Everywhere but it has no Itch.io rule for exactly that reason. However, your comment did tickle something at the back of my memory and and I managed to confirm the source of the problem.

Buried deep within three nested tabbed panes in the Advanced section of NoScript's Options dialog is an "Enable Automatic Secure Cookie Management" checkbox which is checked by default.

(NoScript > Options > Advanced > HTTPS > Cookies > Enable Automatic Secure Cookies Management)

Unchecking that and reloading the HTTP page allowed the cookie to be set for it. Once done, re-enabling it doesn't seem to hide the cookie again during the current browsing session.

**Comment by leafo** [comment]
Thanks for investigating.

Obviously this is just a work around, not a solution to the problem. I'll try to get a wildcard cert deployed on game pages soon.

**Comment by leafo** [comment]
HTTPS wildcard cert now deployed, https works everywhere
