### ISSUE TITLE
Add way to copy Bitcoin address (not bitcoin: scheme, just hash) to checkout page

### ISSUE THREAD

**Issue by fasterthanlime** [leafo/itch.io#155]
Right now it's unpractical to select the text & copy paste as one has to start selection outside the control, otherwise browsers will enter drag&drop mode.

**Comment by kilorat** [comment]
And maybe a QR code too, not sure if that's worth its own issue.

**Comment by fasterthanlime** [comment]
But.. but we do have a QR code?

<img width="696" alt="screen shot 2015-07-09 at 11 30 59" src="https://cloud.githubusercontent.com/assets/7998310/8592245/06d68044-262e-11e5-9e57-41b8737e3975.png">

Or is it broken for some? It is generated on the client using JavaScript, maybe it breaks in old browsers?

**Comment by kilorat** [comment]
oops you're right, ignore that comment :)
