### ISSUE TITLE
show game jam dates in an international format

### ISSUE THREAD

**Issue by EmilyBoegheim** [leafo/itch.io#176]
Currently, the closing date for submission of game jam games is shown in the American MM/DD/YYYY format. I find that even if it's obvious a date is in that format, I still have to stop and consciously parse each part of the date in order to read it. Could you please change the date format to something unambiguous and easily readable for international audiences, e.g. "23 July 2015"?

**Comment by fasterthanlime** [comment]
Good catch, thanks! Fix is on its way.

**Comment by fasterthanlime** [comment]
Fix deployed, example page: http://itch.io/jam/a-game-by-its-cover-2015
