### ISSUE TITLE
SWF always says "loading swf for the first time"

### ISSUE THREAD

**Issue by Softwave** [leafo/itch.io#184]
It doesn't seem to matter how long I wait - any SWF I upload says "loading swf for the first time" and never loads. Instead the message disappears quickly leaving the page without a game on it. 

I am using HaxeFlixel (though it doesn't matter what framework I use - and SWF does this) and the issue is mentioned in the [HaxeFlixel google groups](https://groups.google.com/forum/embed/?place=forum%2Fhaxeflixel&showsearch=true&showpopout=true&showtabs=true&parenturl=http%3A%2F%2Fhaxeflixel.com%2Fforum%2F#!topic/haxeflixel/tcUQDkLZp0M).

**Comment by fasterthanlime** [comment]
In the HaxeFlixel group, the fact that the server serves gzipped files has been mentioned, but I don't think it has anything to do with this issue.

Looking at the 'size extraction' code, I'm suspecting the following:

  * python2 or some modules (pylzma?) might be missing
  * swfdump might be missing (part of swftools)

**Comment by leafo** [comment]
Fixed now, sorry about the trouble. Was from missing dependencies and server move.
