### ISSUE TITLE
“Pequod” is damaged and can’t be opened. You should move it to the Trash.

### ISSUE THREAD

**Issue by angelbomb** [leafo/itch.io#193]
I just downloaded Peqoud and can't get any further than this. Any help?

**Comment by fasterthanlime** [comment]
Hey, this is the issue tracker for the itch.io website, not any particular game.

Please contact the developer directly - if you can't find a way to, shoot us an e-mail at support@itch.io, we'll help you with that :)

**Comment by leafo** [comment]
@angelbomb this is most likely apple gatekeeper, have you tried disabling it?

**Comment by angelbomb** [comment]
Thanks Amos,

Sorry about that. My bad!

Todd
-
Todd Thyberg
Owner/Creative Director

Angel Bomb
www.angelbomb.com <http://www.angelbomb.com/>
612-770-1153
