### ISSUE TITLE
Invalid verification codes on login/enabling TOTP

### ISSUE THREAD

**Issue by Tectorum** [leafo/itch.io#201]
I haven't been able to log into Itch.io using two-factor authentication recently via Google Authenticator. 

I verified that my phone had the correct (automatically set) time [as suggested](http://itch.io/developers/two-factor-authentication), and verified that I could log into other sites using Google Authenticator (i.e., Google Mail and other Google sites I use), so the phone time appears correct, as does Google Authenticator. I had previously enabled TOTP for both the Google sites and Itch.io on the same day, sequentially.

I was able to successfully log into itch.io using a recovery key. I then disabled two-factor authentication and attempted to re-enable it. However, I receive another "Invalid verification code" error upon trying to do so. I've used both the QR code and, when that failed, the manual secret. This also failed.

Are there other steps I should try? Did something change with the server time?

**Comment by leafo** [comment]
Was an issue with the server, the clock sync daemon wasn't on and the time drifted too far off. Fixed now, thanks.
