### ISSUE TITLE
in game metadata, have two chinese language tag options -- Simplified Chinese and Traditional Chinese

### ISSUE THREAD

**Issue by radiatoryang** [leafo/itch.io#203]
there's a lot of politics involved in what we call "chinese" etc. -- but know that there are 2 different writing systems, and Wikipedia and Steam distinguish between both, so itch probably should too

**Comment by leafo** [comment]
thanks, I added the two new options. I left the non-specifc "Chinese" option until figure out what to do with the games that have already chosen it: http://itch.io/games/lang-zh
