### ISSUE TITLE
"Show on my profile" flag for collections resets every time the "Edit collection" window is opened.

### ISSUE THREAD

**Issue by fasterthanlime** [leafo/itch.io#208]
(Haven't confirmed myself yet, opening issue anwyay)

Report: https://twitter.com/YellowAfterlife/status/636808177540050945

**Comment by felixplesoianu** [comment]
Steps to reproduce:
- visit https://itch.io/my-collections
- click the Permlink (sic) button next to any collection;
- now click the Edit Collection button.
The "show on my profile" checkbox will be unchecked, and checking it again before saving will have no effect. You have to go back to My Collections and tick the checkbox there.

Hope this helps.

**Comment by fasterthanlime** [comment]
It does help a lot, thanks!

**Comment by leafo** [comment]
Thanks, sorry about the delay. It's fixed now!
