### ISSUE TITLE
Filename truncation sometimes makes display name longer than without truncation.

### ISSUE THREAD

**Issue by Deozaan** [leafo/itch.io#21]
My filenames are kind of long because I put the version number and the platform in there so people know which one to download at a glance.

I've had problems with the maximum display length in the past since either the platform or the version number would be truncated and people wouldn't know which one to download at a glance. But being able to change the display name has usually gotten enough of it visible that people will know what to get.

However, I just noticed this:

![itch io truncation](https://cloud.githubusercontent.com/assets/227734/2737521/9d9997fe-c67c-11e3-8030-9b1057088960.png)

Each of those files whose name is truncated actually only has 1 more character in the name. e.g., Win64, Android or Linux. But truncating the name and adding the ellipses has used up more characters than it would have without all that hullaballoo.

Any way to make that smarter?

**Comment by fasterthanlime** [comment]
This was fixed a while ago! forgot to close.
