### ISSUE TITLE
Add "phone" as input method under classifications

### ISSUE THREAD

**Issue by Casmo** [leafo/itch.io#215]
Can we have "phone" as input method under classifications?

I'm developing games that are played on TV/PC and controlled by your (smart) phone. A little weird but it works and is great for (local) multiplayer games. E.g.: http://casmo.itch.io/breakout-multiplayer.

**Comment by leafo** [comment]
Done!

http://itch.io/games/input-phone

**Comment by Casmo** [comment]
That is awesome, thanks!
