### ISSUE TITLE
Saving community rules on unlisted jams leads to 404 page

### ISSUE THREAD

**Issue by Guard13007** [leafo/itch.io#218]
1. Create unlisted jam.
2. Click Edit community
3. Click Save

You are sent to what I assume would be the public form of the rules page ( http://itch.io/jam/JAM_NAME/community ) but this gives a 404 error. It still saves any changes, and has a notification saying so:

![Saved changes on 404 community page](https://cloud.githubusercontent.com/assets/1503900/9835552/d3cd6662-59a5-11e5-9dec-c11ff5623541.png)

**Comment by leafo** [comment]
The issue was that the jam is unpublished, not unlisted. Unpublished jams don't have active communities. I added a placeholder page to explain what's going on to replace the 404 page.
