### ISSUE TITLE
Cover image badly cropped/scaled in twitter

### ISSUE THREAD

**Issue by fractilegames** [leafo/itch.io#220]
When posting itch.io links to twitter, the preview image shows only a small part of the cover image. It's also very blurry due to scaling. 

I believe this happens because the cover image is first cropped to square for open graph preview image and Twitter then cuts away a big chucks from top and bottom of that. This is not exactly itch.io's fault, but I hope there's something that can be done about it.

Here's an example:
![twitter-crop](https://cloud.githubusercontent.com/assets/2310335/9982105/634ad26e-5fd9-11e5-948e-bb5282181fe2.png)

**Comment by leafo** [comment]
It should be fixed now, I set the metatags to point to the original version of the image uploaded, and not the cropped version
