### ISSUE TITLE
Update Emails go to paid email instead of primary Itch.io account email.

### ISSUE THREAD

**Issue by Deozaan** [leafo/itch.io#224]
I use a separate email for my PayPal account than what I use for my Itch.io account. Today I got an update email from a developer I bought something from on Itch.io, and it came to my PayPal account instead of to my Itch.io account.

Is there any way we can get emails sent to the "primary email" listed in our Itch.io account instead of the various linked/additional addresses we may have paid with?

**Comment by leafo** [comment]
Fixed
