### ISSUE TITLE
Unsubscribe links apparently broken

### ISSUE THREAD

**Issue by nfd** [leafo/itch.io#230]
Hi there,

In recent mailouts for "Kenney game assets" the unsubscribe link is broken. Clicking the links gives this response:

{"errors":["invalid signature"]}

... and I am not unsubscribed.

**Comment by leafo** [comment]
What's your mail client? Could you send me the URL via email: leafo@itch.io

**Comment by fasterthanlime** [comment]
Saw a tweet exchange in which @leafo said it was solved, reopen if that's not the case.
