### ISSUE TITLE
Post-registration confirmation notification

### ISSUE THREAD

**Issue by Fironet** [leafo/itch.io#242]
After registering to make a comment on a game page the site didn't present any confirmation message, page, or indication I had registered.

Since individual game pages lack a site-wide itch.io header (which normally displays the username on the home page) it would be useful to indicate to the user they have successfully registered, perhaps as a green overlay message at the top or similar.

**Comment by fasterthanlime** [comment]
Good catch @Fironet, there should definitely at least be an I.flash

Btw, I still think the header should always be there for logged in users (can't remember the last time we discussed this @leafo — not sure if the main issue was philosophical (don't clutter game pages) or technical (they're different CSS, need a cleanup first, what about perf))

**Comment by leafo** [comment]
I want to add a persistent header for all logged in users on game pages, just haven't got a chance to do it yet. Need to make an updated design that works for both the page owners and regular users. Can't use the existing red header since it would clash with a lot of game pages.

**Comment by fasterthanlime** [comment]
Looks like @leafo added a site-wide header (barring user pages, which makes sense imho).

Only problem I can see is user dropdown menu pops 'under' action buttons:

![popunder](https://cloud.githubusercontent.com/assets/7998310/11036006/155a536a-86f6-11e5-8efa-65e36dedfda5.png)

**Comment by Fironet** [comment]
Looking good. Cheers @leafo!

Guessing the positioning could be fixed with z-index.

**Comment by leafo** [comment]
woops, sorry about that. fixed now
