### ISSUE TITLE
Payout Requests don't respect customized Itch.io cut?

### ISSUE THREAD

**Issue by Deozaan** [leafo/itch.io#246]
I noticed today that I had a payment from April available for payout. With the amount being so small I decided just this once to set Itch.io's cut to 0% and request the funds.

Now it tells me the payout is pending but it lists Itch.io's cut as 10% even though when I go to the Payment tab of my settings, it is listed as 0%.

Note: I don't really care about not receiving the 10% of the payout. I just think it's a bug that should be fixed. Or if it is working as intended (i.e. 10% is the minimum you can set it to) then this should be clarified and the value in the settings should be restricted so people aren't surprised when it doesn't work the way it says it will work.

**Comment by leafo** [comment]
The itch.io cut is applied at the time of the purchase. You can't change it after the purchases have happened.

**Comment by Deozaan** [comment]
IMO it makes more sense to apply it at the time of payout, but that's good to know. Thanks.

**Comment by Guard13007** [comment]
Shouldn't this be marked closed?

**Comment by fasterthanlime** [comment]
Yup
