### ISSUE TITLE
[Urgent] Listing Info Issue‏

### ISSUE THREAD

**Issue by ysrinivasreddy** [leafo/itch.io#247]
Hello itch.io  Team,

I am Submitted My Application 4 hours back in
 
http://itch.io/jam/leapmotion3djam

Leap Motion 3D Jam Competition,

My Project Link is 

http://itch.io/jam/leapmotion3djam/rate/42881

 when i click visit game its going to the page

http://ysrinivasreddy.itch.io/leap-opticals

But its showing

404: Not Found!

 I am Attached all screenshots regarding Issue

Please Solve My issue as soon as possible.

**Comment by leafo** [comment]
Should be good now
