### ISSUE TITLE
Don't let special characters in filename prevent download from happening

### ISSUE THREAD

**Issue by BreadmanGameDev** [leafo/itch.io#25]
People seem to be downloading my game without any issues, except for one person (so far) who has encountered this error when attempting to download the game file:

“The request signature we calculated does not match the signature you provided. Check your Google secret key and signing method.”

I tried to research the issue, but all I could find were other Google cloud storage users who encountered this issue when uploading code. Weird that it is displaying when this person attempts to download a file from Itch (rather than when uploading something). I wonder if it's a problem with the user's computer or a bug that needs fixing?

**Comment by fasterthanlime** [comment]
Been able to reproduce the bug with a file named "Un élan de poète.zip" on both Firefox OSX and Chrome OSX

**Comment by fasterthanlime** [comment]
This should not happen for any new upload — file names in the bucket are now auto-generated and thus never contain special characters.
