### ISSUE TITLE
Project URL positioning bug on Chrome/OSX

### ISSUE THREAD

**Issue by fasterthanlime** [leafo/itch.io#257]
Reported by e-mail, screenshot:

<img width="669" alt="positioning" src="https://cloud.githubusercontent.com/assets/7998310/11340497/685104e8-91fe-11e5-8e41-e5669123a657.png">

(note: I'm not experiencing this on Chrome/OSX on my retina MBP. Not sure what gives!)

**Comment by leafo** [comment]
fixed
