### ISSUE TITLE
Email never recieved

### ISSUE THREAD

**Issue by Amtera** [leafo/itch.io#260]
I was given WolfQuest as a gift but never got my email.

**Comment by Amtera** [comment]
How do I either get money back for never receiving my game or get the email with the gift?

**Comment by fasterthanlime** [comment]
Hey there! This issue tracker is for general bugs / feature requests.

Could you send us an e-mail to [support@itch.io](mailto:support@itch.io) from the e-mail address you were expecting to receive the gift to? This way your e-mail is not leaked to everyone who browses the issue tracker.

Thanks! :star2:
