### ISSUE TITLE
Widget code has &amp; where & should be

### ISSUE THREAD

**Issue by Guard13007** [leafo/itch.io#267]
As shown here:

![fuuuuuuuck](https://cloud.githubusercontent.com/assets/15093567/11651488/ed28cf5a-9d45-11e5-8431-46cff4044ac9.png)

**Comment by leafo** [comment]
This should work, are you seeing it not work?

**Comment by Guard13007** [comment]
I expected it was an accidental escaping of an & that shouldn't be there.

Now I'm questioning why you do this? It does indeed work, but why would you want to use `&amp;` where & should work?

(Gonna close this then since it's not really a bug.)

**Comment by Guard13007** [comment]
(A quick Google search about it says that it should be escaped because of rare issues with interpreting entities in URLs. TIL, and sorry to bother you about it.)

**Comment by leafo** [comment]
The HTML generator escapes `"` `'` `>` `<` and `&` in any HTML attribute value. `&` has special meaning, eg. why `&amp;` gives the correct result above. Other `&` escape sequences might accidentally be formed and change the value of the string.
