### ISSUE TITLE
Fix itch.io/app link

### ISSUE THREAD

**Issue by fasterthanlime** [leafo/itch.io#273]
Replace `https://nuts.itch.zone` with `https://nuts.itch.zone/download`, some download managers are [not happy with the former](https://twitter.com/RichieStacker/status/676765915686576128)

*edit: fix url*

**Comment by leafo** [comment]
You mean https://nuts.itch.zone/download right?

**Comment by fasterthanlime** [comment]
@leafo ah yep, my bad

**Comment by leafo** [comment]
K deployed

**Comment by fasterthanlime** [comment]
:100:
