### ISSUE TITLE
Update screenshot on itch.io/app

### ISSUE THREAD

**Issue by fasterthanlime** [leafo/itch.io#279]

**Comment by fasterthanlime** [comment]
here's a good one:

![screen shot 2015-12-20 at 19 42 54](https://cloud.githubusercontent.com/assets/7998310/11919405/2283e5a2-a752-11e5-85d0-9b72d3bcbe2a.png)

**Comment by leafo** [comment]
blank thumbnail?

**Comment by fasterthanlime** [comment]
![screen shot 2015-12-20 at 19 49 58](https://cloud.githubusercontent.com/assets/7998310/11919427/deed528c-a752-11e5-9e44-29ef869e00fa.png)

here's an even better one

**Comment by fasterthanlime** [comment]
also would you consider making it slightly higher-res than what's on itch.io/app right now? maybe not original res, but even then with pngcrush it should be reasonable right?

**Comment by leafo** [comment]
retina privilege

**Comment by fasterthanlime** [comment]
> retina privilege

:apple: :apple: :apple:

**Comment by leafo** [comment]
http://itch.io/app

**Comment by fasterthanlime** [comment]
:100:
