### ISSUE TITLE
expose 'payments_disabled'

### ISSUE THREAD

**Issue by fasterthanlime** [leafo/itch.io#288]
and also return min_price == 0 for those, don't leak the db value, it could be a secret

**Comment by fasterthanlime** [comment]
btw, the website has a bug too: if payments are disabled, it'll still display the price label, cf. https://itch.io/search?q=trigger+wendy

**Comment by leafo** [comment]
Two changes to game objects:

* `min_price` only returns a value > 0 if paid status is not free
* added `can_be_bought` field to games

Also fixed the bug on the site
