### ISSUE TITLE
list web downloads in all `uploads` endpoints

### ISSUE THREAD

**Issue by fasterthanlime** [leafo/itch.io#290]
so, /game/GAME_ID/uploads and the one with the download key

mark them as web, e.g. `p_web` true, with an additional field, web_classification = html5, flash, unity, java

**Comment by leafo** [comment]
we don't use `p_web`, it will have a `type` set to something other than `"default"`

**Comment by fasterthanlime** [comment]
yeah that's cool too

**Comment by leafo** [comment]
deployed
