### ISSUE TITLE
Add Amazon App Store in new game / edit game page

### ISSUE THREAD

**Issue by fasterthanlime** [leafo/itch.io#293]
https://twitter.com/jessefreeman/status/678995372237299712

**Comment by Deozaan** [comment]
@fasterthanlime Should this be closed now?

https://twitter.com/fasterthanlime/status/679002807534399489

**Comment by leafo** [comment]
not done yet, I think you snapped another tweet out of context

**Comment by Deozaan** [comment]
@leafo The one I linked was a direct reply to the one @fasterthanlime linked.

Sorry for my confusion. :)

**Comment by fasterthanlime** [comment]
@Deozaan yeah, by "done" I meant sending Jesse an e-mail :)

**Comment by leafo** [comment]
deployed

**Comment by jessefreeman** [comment]
Thanks!
