### ISSUE TITLE
Consider merging claimed / owned keys endpoints

### ISSUE THREAD

**Issue by fasterthanlime** [leafo/itch.io#295]
I'm always grouping them in the app anyway.

key responses in the API could have a field: 'source', 'kind', 'origin' ? that could be either 'claimed', or 'bought'

**Comment by leafo** [comment]
Glad you brought this up. They will be grouped, it's just a quick from before we had owner_id on download keys. I'm going to kill support for methods but we should sync on how we do it

**Comment by fasterthanlime** [comment]
@leafo have one return empty array for a bit ?

**Comment by leafo** [comment]
yup, now deployed
