### ISSUE TITLE
Issue with bullet that cannot be deleted

### ISSUE THREAD

**Issue by crazya02** [leafo/itch.io#297]
The description for my game has a weird glitchy list bullet at the end that I can't move the text cursor to. It can be found at http://crazya02.itch.io/elevacuum

![bulletbug1](https://cloud.githubusercontent.com/assets/16418373/11984391/a4890f54-a96f-11e5-8953-3874f8b6c128.PNG)
![bulletbug2](https://cloud.githubusercontent.com/assets/16418373/11984392/a48c0560-a96f-11e5-9de8-891b61a1adf4.PNG)

**Comment by leafo** [comment]
Strange bug. Our text editor is 3rd party so it's a bit harder to fix bugs on it. It isn't ideal, but you can always enter HTML mode and delete the offending markup:

![](http://leafo.net/shotsnb/2015-12-27_01-27-08.png)


I've fixed your game page for you.
