### ISSUE TITLE
Game crash upon startup

### ISSUE THREAD

**Issue by Eriphia** [leafo/itch.io#298]
Merry Christmas.

I tried to boot this game and it instantly crashes with the following message:

___________________________________________
############################################################################################
FATAL ERROR in Vertex Shader compilation
ShaderName: shader_horizontal_shift

D3DXCompile failed - result

at gml_Object_p_card_Draw_0
############################################################################################

What's going on?

**Comment by leafo** [comment]
Hello,

Please tell us which game your'e having trouble with. This is an issues tracker for the itch.io website, but I can help you get in touch with the developer.

Thanks

**Comment by Eriphia** [comment]
Oh sorry, yeah, it's about the game sandstorm

**Comment by leafo** [comment]
Doesn't look like they're on github, if you send me an email at support@itch.io I can forward the message to them. Or if you have twitter you can contact them yourself: https://twitter.com/managore

**Comment by fasterthanlime** [comment]
> Doesn't look like they're on github

Actually, @managore opened two issues here already :) Don't know if daniel wants to use github to track issues with their games though.

**Comment by Guard13007** [comment]
It just occurred to me that the reason you get so many bug reports for games on here is probably that people are skimming [the support page](http://itch.io/docs/general/support), completely missing where it says "This is not support for individual games." up top, and clicking the links under the "Bugs & feature requests" heading.

Maybe putting that same disclaimer down there as well would help reduce the number of people coming here incorrectly.

**Comment by leafo** [comment]
@fasterthanlime woops

@Guard13007 good idea, I duplicated the message there. I also added the message to `CONTRIBUTING.md`
