### ISSUE TITLE
External uploads have empty 'filename'

### ISSUE THREAD

**Issue by fasterthanlime** [leafo/itch.io#306]

**Comment by leafo** [comment]
What should the filename be? Try to extract it from the URL?

**Comment by fasterthanlime** [comment]
Maybe the filename should remain empty & have another field instead (`external_url` ?)

**Comment by fasterthanlime** [comment]
This issue seems relatively pointless now, but at the time my thinking was:

  * It's useful for the app to be able to determine the file extension of something before even starting to download it
  * On windows, an .exe can only be launched as an .exe if it actually has the .exe file extension
  * Currently with external downloads, the itch app creates a copy of the download with the .exe extension to be able to launch it

I wanted to avoid doing that copy (`mv` is not really practical in case the app is aborted), but I don't feel good about having the itch.io website try to sniff the extension from the URL (in fact, extracting it from the `Content-Disposition` header in the HTTP response would be preferrable, but that won't work with all servers).

I guess there's nothing to do one this one for now. Will re-open in the future if I come up with something actionable
