### ISSUE TITLE
Change text color on HTML in the "edit page"

### ISSUE THREAD

**Issue by matriax** [leafo/itch.io#315]
I'm doing my itchio game page for my next game that will be released this week( if all works correct) and seems that i only can select the font color for the entire page in the "Edit theme" but nothing more?

I tried to use "< font color="yellow" >< / font >" but after leaving the html5 editing disappears ¿? . I saw others pages and all have the same colors so i guess is not allowed or i'm missing something.  I think is a basic thing so if has no been added already maybe there is a reason i don't know?

In that case at least leave us change the color for "Headers", something like that:

![header_color](https://cloud.githubusercontent.com/assets/16635665/12228910/e4a94ab4-b841-11e5-993f-cadff3aca36e.jpg)

Not is a big change but looks better/readable and will give us also the chance to use it to remark some words in other colors,etc...

**Comment by leafo** [comment]
what if you try putting in `style="color: #FFFF00"` on the tag in the HTML mode of the editor?

**Comment by matriax** [comment]
Not worked at least for me, i tried:

<h1 style="color:#ffff00;">About AsteroidX</h1>

And:

<p style="color:#ffff00;"> <h1>About AsteroidX</h1> </p>

None worked, but i found the way i have to use:

<h1 style="color:RGB(255,210,39)">About AsteroidX</h1>

Only works with RGB values. so maybe a color pick selector for H1 etc... like the normal font in edit theme will be useful.

**Comment by leafo** [comment]
hmm interesting, that sounds like a bug.

Regarding the text editor, it's a massive separate project that we don't control. I haven't looked into how simple it would be to extend the functionality.

**Comment by matriax** [comment]
Ok, well, while we have a way to change the color no problem ;)
