### ISSUE TITLE
API docs are unreadable?

### ISSUE THREAD

**Issue by fasterthanlime** [leafo/itch.io#320]
All sample output is on a white bg for me:

http://itch.io/docs/api/serverside

<img width="903" alt="screen shot 2016-01-12 at 12 29 24" src="https://cloud.githubusercontent.com/assets/7998310/12262416/22d5166a-b928-11e5-87fb-454912fe4cd5.png">

**Comment by matriax** [comment]
Same for me, i have to select with the mouse to see what is inside. Is like how the spoiler texts are used :P

**Comment by leafo** [comment]
woops

**Comment by leafo** [comment]
fixed now
