### ISSUE TITLE
How to test if "External Key" works before publish?

### ISSUE THREAD

**Issue by matriax** [leafo/itch.io#327]
I created a "TestAPP" with a download with 0 price. I set some keys in the Distribute->External Keys.

But when i test and click on "Download" i go to a page to download the file but there is no button to "claim the key" and test if works like appears in the faq: https://itch.io/docs/creators/how-buying-works

I guess the APP have to be published or with a minimun price for purchase and give that option, but before that, how to test it?

**Comment by fasterthanlime** [comment]
Hey @matriax, only people who own a page get external keys - the one who download for free, don't.

**Comment by matriax** [comment]
So, then, meanwhile the APP is in private how i can test that the External keys works?

**Comment by fasterthanlime** [comment]
@matriax Generate a download key for yourself (only bulk keys have the option to give you external keys, if I recall correctly)

**Comment by matriax** [comment]
I not want a download key, sorry if i'm explaining bad XD, To be more clear, i want test this option:
http://leafo.net/dump/steam_key.gif

But as you said, seems the only way to do that is publish the game with a X price. As developer there is anyway to test it privately?

**Comment by fasterthanlime** [comment]
@matriax No, no, you're explaining it right, it's me who is explaining it badly.

Give a key **of your game** to yourself, so that you can test it **as if you were a buyer**.

**Comment by fasterthanlime** [comment]
@matriax let me try giving you step by step instructions:

  * From your game page, choose **Edit game**
  * Pick the **Distribute** tab on top
  * Pick the **Download keys** tab on the left
  * Pick **Create bulk key group**
  * In the bulk form:
      * put "Unlock test" in the group name
      * put "1" in count, so you just generate one
      * check "Give access to any Steam or other keys you've added to your game" and "Unlock all files"
      * press "Create bulk key group"
  * The bulk key group now appears — you can press "Get keys", it'll download a file containing your download key (which is a URL)
  * If you go to this URL you should be able to test "getting an external keys" as if you were a buyer

**Comment by matriax** [comment]
I think i'm doing some wrong because actually not works XD

When i do what you are saying i get this page:
http://s29.postimg.org/allloyq53/error.png

And when i click on "Link to my account" i get to other page with only this:
{"errors":{}}

URL: "http://kronbits.itch.io/test/claim-key" .

I generate one of the key, test yourself to see if works, maybe is something wrong on my side:
http://kronbits.itch.io/test/download/fasterthanlime-2XRVQJSkghZzCat3FSBuUG-ss74pNtowtkFVXPQXKjxUKXhcWj

Works?

**Comment by fasterthanlime** [comment]
@matriax Hmm you still need one valid upload I think. Normally you can't buy a game that has 0 uploads, which would explain why it errors.

**Comment by fasterthanlime** [comment]
@matriax Try uploading a .txt file

**Comment by matriax** [comment]
There is a .txt file uploaded XD see:
http://kronbits.itch.io/test?secret=yDjgOrXSXukmRFk97EB21o6kA

**Comment by fasterthanlime** [comment]
@matriax the key you gave me didn't work because the project was set to "Private" — setting it to "Public restricted" allowed me to claim it, and now I can claim external keys from my download page :) So, it works!

**Comment by matriax** [comment]
Ah great! Yes, thanks for the info now works perfect ;) .
