### ISSUE TITLE
When replacing files, order changes

### ISSUE THREAD

**Issue by slowriot** [leafo/itch.io#44]
When uploading a file of the same filename, it replaces the existing file with name and settings kept (as is desired behaviour), but the newly replaced file gets moved to the bottom of the list.  It would be nice if the file kept its list position, as well.

A bonus feature would be if the last upload date for that file could be seen at a glance, too.

**Comment by Deozaan** [comment]
When I update files, they retain the same order. Has this been fixed? @fasterthanlime

**Comment by fasterthanlime** [comment]
@Deozaan yup, was reported on twitter and I fixed it, forgot it was on github too. Thanks!
