### ISSUE TITLE
Navigate screenshot set with left/right

### ISSUE THREAD

**Issue by hryx** [leafo/itch.io#46]
When viewing the screenshots on a game page, I'd like to be able to navigate through them by hitting the left/right keys or clicking on navigation buttons on either side. This is smoother than un-zooming from an image and then selecting another.

Not sure if you're using Lightbox for image viewing, but if so I think all you have to do is put the group of images in a "set".

(And if it is Lightbox, thank you for not using the annoyingly slow expand/collapse animations :goat:)

**Comment by leafo** [comment]
Screenshot browser got some updates thanks to @fasterthanlime
