### ISSUE TITLE
Support cryptocurrencies

### ISSUE THREAD

**Issue by aeickhoff** [leafo/itch.io#5]
I'm new to cryptocurrencies, so someone else might have good suggestions for according payment processors with APIs that fit itch.io's model - but I added the issue anyways, because I think digital goods like games are a nice, low-risk way to try out and establish cryptocurrencies.

**Comment by fasterthanlime** [comment]
![](http://i.imgur.com/TuieiRw.png)

http://blog.itch.io/post/120285706519/introducing-bitcoin-support

Closing! :shipit:

**Comment by dragonDScript** [comment]
Hi! Is this supported yet?

**Comment by shivaenigma** [comment]
It would be good to reconsider this. Blockonomics is a very good option and have too [payment widgets](https://www.blockonomics.co/views/bitcoin_payment_widget.html) / API via which you can easily implement it
