### ISSUE TITLE
Install instructions hidden if HTML game even if download provided

### ISSUE THREAD

**Issue by icbat** [leafo/itch.io#59]
When I add a downloadable game to an HTML project, I can only edit the install instructions if I select Downloadable. They'll still display regardless, if I want to add any or change existing instructions, I have to toggle it back to a Downloadable, edit, then toggle back to HTML.

Minor nitpick, of course =)

**Comment by fasterthanlime** [comment]
This was fixed recently, thanks for reporting!

**Comment by fasterthanlime** [comment]
This has been fixed and deployed!

Install instructions' edit panel will now be visible for all 1) downloadable games or 2) games with at least one file that's not playable in the browser.

:shipit:
