### ISSUE TITLE
Don't autostart web games please

### ISSUE THREAD

**Issue by parachutingturtle** [leafo/itch.io#67]
While browsing itch.io, I would prefer to have the option to read about a game and/or see screenshots before the unity web player loads the whole thing up for me. On the frontpage all I see is a title and a thumbnail, I click it because I want to know more, not because I want to load the game.

Cheers!

~~(PS. it would also be really great if people didn't have to make github or twitter accounts just to contact you.)~~

**Comment by fasterthanlime** [comment]
@leafo looks like the popup is implemented now, is there anything else planned to be done for this?

**Comment by leafo** [comment]
Yeah, I'd prefer to keep games running immediately is it's done now.
