### ISSUE TITLE
Add browse filters to tag pages

### ISSUE THREAD

**Issue by felixplesoianu** [leafo/itch.io#70]
I often browse games by tags rather than platform and genre, and I have to slog through all those titles lacking a version for my platform. I use Linux, see, so I can't run a Win/Mac game. Or, for that matter, a web game requiring the Unity plugin. It would be nice to have some sort of permanent filtering by platform I can save in my user settings. Thank you very much.

**Comment by leafo** [comment]
It's been there for a while! http://blog.itch.io/post/132281735704/enhanced-browsing

**Comment by Guard13007** [comment]
Uhh @leafo what about this part of their request?

> some sort of permanent filtering by platform I can save in my user settings

**Comment by felixplesoianu** [comment]
@Guard13007 Thanks, but I can live without that. There are more important issues now.
