### ISSUE TITLE
Generate Download-Keys (Multiple at once)

### ISSUE THREAD

**Issue by Retrific** [leafo/itch.io#71]
Hey, currently it's only possible to generate download url's (one per time), but it would be much better if you could generate Download-keys that can be activated. Just like for example on Steam or Desura.
So that you can generate let's say 100 Keys at once.

**Comment by fasterthanlime** [comment]
The feature's been deployed last Valentine's Day:

  * http://itchio.tumblr.com/post/111004127554/bulk-key-generation-for-sellers

Closing!
