### ISSUE TITLE
Feature request: bundles of games from different devs

### ISSUE THREAD

**Issue by empty-fortress** [leafo/itch.io#80]
By bundle I mean selling selling one or more games credited to more than one itch.io dev account, and have the system auto-split the money from the sales between each credited party (to avoid having the person making the bundle get all the money and have to split it back between everyone, which means more fees and potential issues).

Such a system could be used for bundles of games, but also collaborations, themed compilations, experimental game dev (something like Experiment 12, but there are many other possibilities)

**Comment by Deozaan** [comment]
I think this has recently been completed. :+1:

**Comment by fasterthanlime** [comment]
Why yes indeed, forgot to close that one. Thanks for the ping! :shipit:
