### ISSUE TITLE
Feature request: Ability to disable downloads (without deleting them)

### ISSUE THREAD

**Issue by adambiser** [leafo/itch.io#82]
Having a checkbox to make downloads available/unavailable from the game page would make it easy to roll back to a previous version if ever needed.

Allowing downloads to be disabled would also retain their download count in the "File download counts" area of the analytics page since deleting a download removes the count for that file.

**Comment by fasterthanlime** [comment]
Looks like this could be advantageously handled in a more complete 'version' feature. Definitely going to take a look at that.

**Comment by adambiser** [comment]
Yes, that would be very nice.  Thank you!

**Comment by adambiser** [comment]
I see that there is now a "Hide this file and prevent it from being downloaded" option for files.  This works well for non-demo files.  Files marked as demo files still appear on the game page, but say "Invalid upload" when clicking them.

Thanks for adding this!

**Comment by fasterthanlime** [comment]
Ha should've closed a while ago! Demo files are correctly hidden now, too.
