### ISSUE TITLE
iframes in description not rendered correctly

### ISSUE THREAD

**Issue by slowriot** [leafo/itch.io#86]
Iframes inserted manually in the html edit of the main description display correctly in preview, but not in the game itself.  Two examples at http://voxelstorm.itch.io/golfxtrm

With the bandcamp embed widget, preview:
![](http://i.imgur.com/FCm2IFx.png)
Main page:
![](http://i.imgur.com/WmxEUXh.png)

And with the facebook social widget, preview:
![](http://i.imgur.com/juBN7Ps.png)
Main page:
![](http://i.imgur.com/sYWRNNa.png)

Note the iframes are both horizontally squashed and vertically truncated.

**Comment by leafo** [comment]
Sorry for delay, should be fixed now. Was an issue with sanitizing CSS.
