### ISSUE TITLE
Separate auto-email after purchase in case of late verification.

### ISSUE THREAD

**Issue by antcase** [leafo/itch.io#9]
It seems for a small amount of people getting the download email after purchasing a game isn't immediate, which I heard is something to do with PayPal's verification system.

But it might be nice if purchasers always received a separate email immediately after purchase just explaining that sometimes the process can take a few hours.

**Comment by leafo** [comment]
Closing this since I've since refactored how I check for purchase completion, emails should be sent instantly.
