### ISSUE TITLE
Re-uploading a file with the same filename doesn't update.

### ISSUE THREAD

**Issue by Norgg** [leafo/itch.io#93]
When attempting to upload a new version of our game the download remained the old version, even after deleting the old version from the site and re-uploading.  Have worked around it by re-naming the file and uploading it, but now I can't change the display name of the new file.

The game page I'm having the problems with is http://voxelstorm.itch.io/advertcity/

**Comment by Norgg** [comment]
The Linux version seems to have uploaded okay, can't check the OSX version myself.

**Comment by leafo** [comment]
Should be fixed now
