### ISSUE TITLE
Verify file size limits are showing errors on game/appearance editors

### ISSUE THREAD

**Issue by leafo** [leafo/itch.io#95]
https://twitter.com/Ragzouken/status/443576747221454848/photo/1

**Comment by fasterthanlime** [comment]
@moonscript Wasn't that fixed, merged & deployed last month?

**Comment by MoonScript** [comment]
@fasterthanlime you have the wrong guy...

**Comment by fasterthanlime** [comment]
@MoonScript so sorry x) that must happen all the time.

@leafo bleep bloop.
